CommunityLeagues/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CommunityLeagues.Models
{
    public class HomeViewModel
    {
        public List<Game> Games { get; set; }
        public List<Player> Players { get; set; }
        public List<Team> Teams { get; set; }
    }
}

CommunityLeagues/Controllers/HomeController.cs
using CommunityLeagues.DAL;
using CommunityLeagues.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CommunityLeagues.Controllers
{
    public class HomeController : Controller
    {
        LeaguesContext db;

        public ActionResult Index(LeaguesContext db)
        {
            HomeViewModel homeVM = new HomeViewModel()
            {
                Games = db.Games.ToList(),
                Teams = db.Team.ToList(),
                Players = db.Players.ToList()
            };

            return View(homeVM);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CommunityLeagues/Controllers/TournamentController.cs
using CommunityLeagues.DAL;
using CommunityLeagues.Infrastructure;
using CommunityLeagues.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CommunityLeagues.Controllers
{
    public class TournamentController : Controller
    {

        private LeaguesContext db;
        private TournamentManager tournamentManager;
        //private TeamManager teamManager;
        //private PlayerManager playerManager;

        public TournamentController(LeaguesContext db, TournamentManager tm)
        {
            this.db = db;
            tournamentManager = tm;
        }
        // GET: Tournament
        public ActionResult Index(int id)
        {
            Tournament tournament = tournamentManager.GetTournament(id);
            TournamentViewModel tournamentVM = new TournamentViewModel()
            {
                TournamentId = tournament.TournamentId,
                Award = tournament.Award,
                Name = tournament.Name,
                Teams = tournament.Teams.OrderBy(a => a.Name).ToList(),
                dateStart = tournament.dateStart
            };

            return View(tournamentVM);
        }

        [Authorize]
        public ActionResult SignUp(int id)
        {
            var userId = User.Identity.GetUserId();

            var pm = new PlayerManager(db);
            var tm = new TeamManager(db);

            var signupVM = new SignUpViewModel()
            {
                Team = tm.GetTeam(userId),
                Tournament = tournamentManager.GetTournament(id),
                EnoughRoleOfPlayer = true,
                TeamIsAlreadySignUp = false
            };

            if (tm.GetTeamPlayer(userId).TeamRole != Roles.Leader)
            {
                signupVM.EnoughRoleOfPlayer = false;
            }
            else if (tournamentManager.IsTeamSignUp(signupVM.Team.TeamId, id))
            {
                signupVM.TeamIsAlreadySignUp = true;
            }

            return View(signupVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(SignUpViewModel sm)
        {
            var team = sm.Team;
            var result = db.Team.Where(a => a.TeamId == team.TeamId).FirstOrDefault();
            result.TournamentId = sm.Tournament.TournamentId;
            db.SaveChanges();

            return RedirectToAction("Index", new { id = sm.Tournament.TournamentId });
        }
    }
}

CommunityLeagues/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CommunityLeagues/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CommunityLeagues/Views/Home/Index.cshtml
@model CommunityLeagues.Models.HomeViewModel

@{
    ViewBag.Title = "Community Leagues";
}

<div class="row" style="margin-top: 50px">
    <div class="col-md-4">
        <h2>List of games:</h2>
        <ul style="min-height: 200px">
            @foreach (var game in Model.Games)
            {
                <li>
                    @game.Name
                </li>
            }
        </ul>

    </div>
    <div class="col-md-4">
        <h2>Players:</h2>
        <ul style="min-height: 200px">
            @foreach (var player in Model.Players)
            {
                <li>
                    @player.Name
                </li>
            }
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Teams:</h2>
        <ul style="min-height: 200px">
            @foreach (var team in Model.Teams)
            {
                <li>
                    @team.Name
                </li>
            }
        </ul>
    </div>
</div>


<div class="row" style="margin-top: 50px">
    <div class="col-md-4">
        <p>
            We don't support more games yet. <br />
            Check us in the future!
        </p>
    </div>
    <div class="col-md-4">
        <p>
            Invite more players to our site!
        </p>
    </div>
    <div class="col-md-4">
        <p>
            Create or join to any team!

        </p>
    </div>
</div>


<p style="margin-top: 50px">
    Prepare your team and soon you will be able to play matches in our first tournament : @Html.ActionLink("Click", "Index", "Tournament" , new { id = 1 }, null)
</p>
<p>
    Currently you are available to do :
    <ul>
        <li>
            Register your account
        </li>
        <li>
            Register your first player to available game.
        </li>
        <li>
            Create a new team and invite others to your team.
        </li>
        <li>
            Ask any leader to add you to his team.
        </li>
        <li>
            As leader you can add your team to new tournament!
        </li>
        <li>
            Be part of our community and wait for more!
        </li>
    </ul>
</p>